# Generated by Django 2.2.1 on 2020-01-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20200123_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospital'},
        ),
    ]
